{
  status: 200,
  statusText: 'OK',
  headers: {
    server: 'GitHub.com',
    date: 'Mon, 21 Mar 2022 23:31:56 GMT',
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'public, max-age=60, s-maxage=60',
    vary: 'Accept, Accept-Encoding, Accept, X-Requested-With',
    etag: 'W/"293806110fbb34813c16bb907e92631ff6a8ba729b0aa562d73de54b7595252b"',
    'x-github-media-type': 'github.v3',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    'access-control-allow-origin': '*',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'x-frame-options': 'deny',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '0',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    'content-security-policy': "default-src 'none'",
    'x-ratelimit-limit': '60',
    'x-ratelimit-remaining': '58',
    'x-ratelimit-reset': '1647909069',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '2',
    'accept-ranges': 'bytes',
    'transfer-encoding': 'chunked',
    'x-github-request-id': 'F9FB:079C:CA4119:D9330D:62390AEC',
    connection: 'close'
  },
  config: {
    url: 'https://api.github.com/users/seanatrinh/repos',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.4'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.github.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.github.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 25,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /users/seanatrinh/repos HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.21.4\r\n' +
      'Host: api.github.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/users/seanatrinh/repos',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 200,
      statusMessage: 'OK',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.github.com/users/seanatrinh/repos',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 48,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.github.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.github.com/users/seanatrinh/repos',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  data: [
    {
      id: 451337878,
      node_id: 'R_kgDOGubelg',
      name: 'hofPractice',
      full_name: 'seanatrinh/hofPractice',
      private: false,
      owner: [Object],
      html_url: 'https://github.com/seanatrinh/hofPractice',
      description: 'hofPractice',
      fork: true,
      url: 'https://api.github.com/repos/seanatrinh/hofPractice',
      forks_url: 'https://api.github.com/repos/seanatrinh/hofPractice/forks',
      keys_url: 'https://api.github.com/repos/seanatrinh/hofPractice/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/seanatrinh/hofPractice/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/seanatrinh/hofPractice/teams',
      hooks_url: 'https://api.github.com/repos/seanatrinh/hofPractice/hooks',
      issue_events_url: 'https://api.github.com/repos/seanatrinh/hofPractice/issues/events{/number}',
      events_url: 'https://api.github.com/repos/seanatrinh/hofPractice/events',
      assignees_url: 'https://api.github.com/repos/seanatrinh/hofPractice/assignees{/user}',
      branches_url: 'https://api.github.com/repos/seanatrinh/hofPractice/branches{/branch}',
      tags_url: 'https://api.github.com/repos/seanatrinh/hofPractice/tags',
      blobs_url: 'https://api.github.com/repos/seanatrinh/hofPractice/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/seanatrinh/hofPractice/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/seanatrinh/hofPractice/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/seanatrinh/hofPractice/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/seanatrinh/hofPractice/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/seanatrinh/hofPractice/languages',
      stargazers_url: 'https://api.github.com/repos/seanatrinh/hofPractice/stargazers',
      contributors_url: 'https://api.github.com/repos/seanatrinh/hofPractice/contributors',
      subscribers_url: 'https://api.github.com/repos/seanatrinh/hofPractice/subscribers',
      subscription_url: 'https://api.github.com/repos/seanatrinh/hofPractice/subscription',
      commits_url: 'https://api.github.com/repos/seanatrinh/hofPractice/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/seanatrinh/hofPractice/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/seanatrinh/hofPractice/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/seanatrinh/hofPractice/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/seanatrinh/hofPractice/contents/{+path}',
      compare_url: 'https://api.github.com/repos/seanatrinh/hofPractice/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/seanatrinh/hofPractice/merges',
      archive_url: 'https://api.github.com/repos/seanatrinh/hofPractice/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/seanatrinh/hofPractice/downloads',
      issues_url: 'https://api.github.com/repos/seanatrinh/hofPractice/issues{/number}',
      pulls_url: 'https://api.github.com/repos/seanatrinh/hofPractice/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/seanatrinh/hofPractice/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/seanatrinh/hofPractice/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/seanatrinh/hofPractice/labels{/name}',
      releases_url: 'https://api.github.com/repos/seanatrinh/hofPractice/releases{/id}',
      deployments_url: 'https://api.github.com/repos/seanatrinh/hofPractice/deployments',
      created_at: '2022-01-24T06:09:40Z',
      updated_at: '2022-01-28T02:37:53Z',
      pushed_at: '2022-01-28T02:37:50Z',
      git_url: 'git://github.com/seanatrinh/hofPractice.git',
      ssh_url: 'git@github.com:seanatrinh/hofPractice.git',
      clone_url: 'https://github.com/seanatrinh/hofPractice.git',
      svn_url: 'https://github.com/seanatrinh/hofPractice',
      homepage: null,
      size: 124,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 472459902,
      node_id: 'R_kgDOHCkqfg',
      name: 'promised-playground',
      full_name: 'seanatrinh/promised-playground',
      private: false,
      owner: [Object],
      html_url: 'https://github.com/seanatrinh/promised-playground',
      description: 'A place to explore AJAX and Promises',
      fork: true,
      url: 'https://api.github.com/repos/seanatrinh/promised-playground',
      forks_url: 'https://api.github.com/repos/seanatrinh/promised-playground/forks',
      keys_url: 'https://api.github.com/repos/seanatrinh/promised-playground/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/seanatrinh/promised-playground/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/seanatrinh/promised-playground/teams',
      hooks_url: 'https://api.github.com/repos/seanatrinh/promised-playground/hooks',
      issue_events_url: 'https://api.github.com/repos/seanatrinh/promised-playground/issues/events{/number}',
      events_url: 'https://api.github.com/repos/seanatrinh/promised-playground/events',
      assignees_url: 'https://api.github.com/repos/seanatrinh/promised-playground/assignees{/user}',
      branches_url: 'https://api.github.com/repos/seanatrinh/promised-playground/branches{/branch}',
      tags_url: 'https://api.github.com/repos/seanatrinh/promised-playground/tags',
      blobs_url: 'https://api.github.com/repos/seanatrinh/promised-playground/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/seanatrinh/promised-playground/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/seanatrinh/promised-playground/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/seanatrinh/promised-playground/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/seanatrinh/promised-playground/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/seanatrinh/promised-playground/languages',
      stargazers_url: 'https://api.github.com/repos/seanatrinh/promised-playground/stargazers',
      contributors_url: 'https://api.github.com/repos/seanatrinh/promised-playground/contributors',
      subscribers_url: 'https://api.github.com/repos/seanatrinh/promised-playground/subscribers',
      subscription_url: 'https://api.github.com/repos/seanatrinh/promised-playground/subscription',
      commits_url: 'https://api.github.com/repos/seanatrinh/promised-playground/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/seanatrinh/promised-playground/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/seanatrinh/promised-playground/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/seanatrinh/promised-playground/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/seanatrinh/promised-playground/contents/{+path}',
      compare_url: 'https://api.github.com/repos/seanatrinh/promised-playground/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/seanatrinh/promised-playground/merges',
      archive_url: 'https://api.github.com/repos/seanatrinh/promised-playground/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/seanatrinh/promised-playground/downloads',
      issues_url: 'https://api.github.com/repos/seanatrinh/promised-playground/issues{/number}',
      pulls_url: 'https://api.github.com/repos/seanatrinh/promised-playground/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/seanatrinh/promised-playground/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/seanatrinh/promised-playground/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/seanatrinh/promised-playground/labels{/name}',
      releases_url: 'https://api.github.com/repos/seanatrinh/promised-playground/releases{/id}',
      deployments_url: 'https://api.github.com/repos/seanatrinh/promised-playground/deployments',
      created_at: '2022-03-21T18:18:56Z',
      updated_at: '2022-03-18T17:39:46Z',
      pushed_at: '2022-03-17T18:59:10Z',
      git_url: 'git://github.com/seanatrinh/promised-playground.git',
      ssh_url: 'git@github.com:seanatrinh/promised-playground.git',
      clone_url: 'https://github.com/seanatrinh/promised-playground.git',
      svn_url: 'https://github.com/seanatrinh/promised-playground',
      homepage: null,
      size: 33,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main'
    },
    {
      id: 467203113,
      node_id: 'R_kgDOG9j0KQ',
      name: 'reactjs-tmdb-app',
      full_name: 'seanatrinh/reactjs-tmdb-app',
      private: false,
      owner: [Object],
      html_url: 'https://github.com/seanatrinh/reactjs-tmdb-app',
      description: "Responsive React 'The Movie Database' (TMDb) App",
      fork: true,
      url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app',
      forks_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/forks',
      keys_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/teams',
      hooks_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/hooks',
      issue_events_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/issues/events{/number}',
      events_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/events',
      assignees_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/assignees{/user}',
      branches_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/branches{/branch}',
      tags_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/tags',
      blobs_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/languages',
      stargazers_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/stargazers',
      contributors_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/contributors',
      subscribers_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/subscribers',
      subscription_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/subscription',
      commits_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/contents/{+path}',
      compare_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/merges',
      archive_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/downloads',
      issues_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/issues{/number}',
      pulls_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/labels{/name}',
      releases_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/releases{/id}',
      deployments_url: 'https://api.github.com/repos/seanatrinh/reactjs-tmdb-app/deployments',
      created_at: '2022-03-07T17:58:28Z',
      updated_at: '2022-03-05T15:11:46Z',
      pushed_at: '2021-02-12T10:00:09Z',
      git_url: 'git://github.com/seanatrinh/reactjs-tmdb-app.git',
      ssh_url: 'git@github.com:seanatrinh/reactjs-tmdb-app.git',
      clone_url: 'https://github.com/seanatrinh/reactjs-tmdb-app.git',
      svn_url: 'https://github.com/seanatrinh/reactjs-tmdb-app',
      homepage: 'https://skempin.github.io/reactjs-tmdb-app/',
      size: 8458,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: [Object],
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 455465648,
      node_id: 'R_kgDOGyXasA',
      name: 'recursion-prompts',
      full_name: 'seanatrinh/recursion-prompts',
      private: false,
      owner: [Object],
      html_url: 'https://github.com/seanatrinh/recursion-prompts',
      description: 'Repository of prompts to be solved using recursion',
      fork: true,
      url: 'https://api.github.com/repos/seanatrinh/recursion-prompts',
      forks_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/forks',
      keys_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/teams',
      hooks_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/hooks',
      issue_events_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/issues/events{/number}',
      events_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/events',
      assignees_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/assignees{/user}',
      branches_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/branches{/branch}',
      tags_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/tags',
      blobs_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/languages',
      stargazers_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/stargazers',
      contributors_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/contributors',
      subscribers_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/subscribers',
      subscription_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/subscription',
      commits_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/contents/{+path}',
      compare_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/merges',
      archive_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/downloads',
      issues_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/issues{/number}',
      pulls_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/labels{/name}',
      releases_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/releases{/id}',
      deployments_url: 'https://api.github.com/repos/seanatrinh/recursion-prompts/deployments',
      created_at: '2022-02-04T08:00:45Z',
      updated_at: '2022-02-01T00:39:30Z',
      pushed_at: '2022-01-24T23:40:48Z',
      git_url: 'git://github.com/seanatrinh/recursion-prompts.git',
      ssh_url: 'git@github.com:seanatrinh/recursion-prompts.git',
      clone_url: 'https://github.com/seanatrinh/recursion-prompts.git',
      svn_url: 'https://github.com/seanatrinh/recursion-prompts',
      homepage: null,
      size: 523,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    },
    {
      id: 469190583,
      node_id: 'R_kgDOG_dHtw',
      name: 'system-design-primer',
      full_name: 'seanatrinh/system-design-primer',
      private: false,
      owner: [Object],
      html_url: 'https://github.com/seanatrinh/system-design-primer',
      description: 'Learn how to design large-scale systems. Prep for the system design interview.  Includes Anki flashcards.',
      fork: true,
      url: 'https://api.github.com/repos/seanatrinh/system-design-primer',
      forks_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/forks',
      keys_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/teams',
      hooks_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/hooks',
      issue_events_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/issues/events{/number}',
      events_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/events',
      assignees_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/assignees{/user}',
      branches_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/branches{/branch}',
      tags_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/tags',
      blobs_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/languages',
      stargazers_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/stargazers',
      contributors_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/contributors',
      subscribers_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/subscribers',
      subscription_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/subscription',
      commits_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/contents/{+path}',
      compare_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/merges',
      archive_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/downloads',
      issues_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/issues{/number}',
      pulls_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/labels{/name}',
      releases_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/releases{/id}',
      deployments_url: 'https://api.github.com/repos/seanatrinh/system-design-primer/deployments',
      created_at: '2022-03-12T20:16:46Z',
      updated_at: '2022-03-12T20:16:36Z',
      pushed_at: '2022-03-07T16:32:00Z',
      git_url: 'git://github.com/seanatrinh/system-design-primer.git',
      ssh_url: 'git@github.com:seanatrinh/system-design-primer.git',
      clone_url: 'https://github.com/seanatrinh/system-design-primer.git',
      svn_url: 'https://github.com/seanatrinh/system-design-primer',
      homepage: '',
      size: 11154,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: [Object],
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: 'public',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'master'
    }
  ]
}